apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flask-app-envoy-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: flask-app-envoy    
  template:
    metadata:
      labels:
        app: flask-app-envoy 
    spec:
      containers:
      - name: my-app
        image: senlinzhan/my-app:v0.1
      - name: envoy
        image: lyft/envoy:latest
        command: ["/usr/local/bin/envoy"]
        args:
        - "--config-path /etc/envoy/envoy.json"
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - name: envoy-config
          mountPath: /etc/envoy
      volumes:
      - name: envoy-config
        configMap:
          name: envoy-config
